### ISSUE TITLE
Re-Arrange grade sheet to new format

### ISSUE THREAD

**Issue by john-csula** [csula/cs454-winter-2016#3]
Can we re-arrange grade sheet so that it has the following?

```
Team Name, Last Name, First, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 2.1, 2.2, late-flag, total
```

Where `1.1` - `1.3` are part of the first question, `1.4` and `1.5` are collaboration and comprehension, `1.6` is bonus, and `2.1` and `2.2` are part of the second question.  `late-flag` will be given to those team that are late.

**Comment by rcliao** [comment]
done. Please check the sheet
